install.packages("sqldf")
install.packages("ggplot2")
install.packages("twitteR")
install.packages("wordcloud")
install.packages("googleVis")
install.packages("stringr")
install.packages("tm")
library(twitteR)
library(plyr)
library(ROAuth)
library(RCurl)
library("sqldf", lib.loc="~/R/win-library/3.2")
library("sqldf", lib.loc="~/Library/R/3.2/library")
library("sqldf", lib.loc="/Library/Frameworks/R.framework/Versions/3.2/Resources/library")
library("ggplot2")
library("ggplot2", lib.loc="~/R/win-library/3.2")
library("ggplot2", lib.loc="~/Library/R/3.2/library")
library("ggplot2", lib.loc="/Library/Frameworks/R.framework/Versions/3.2/Resources/library")
library(stringr)
library(wordcloud)
library("RColorBrewer")
library("brew")
library("magrittr")
library("tm")
library("googleVis")
library("stringr")
